name: AutomationForBlogApp
env:
  APP_NAME: "blogapp"
  DEPLOY_PACKAGE_NAME: "jar-app-ver${{github.sha}}"
  AWS_REGION_NAME: "us-east-1"
  ACCOUNT_ID: "736639143360"
  JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

on:
  push:
    branches:
      - main
      
jobs:
  buildJar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print message
      run: echo "This job is for build jar"
    
    - name: Git clone
      uses: actions/checkout@v2
    
    - name: Configure AWS credential
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}} 
        aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
        aws-region: ${{env.AWS_REGION_NAME}}
    
    - name: Set up Java 17
      run: |
        sudo apt-get install openjdk-17-jdk
        sudo update-alternatives --install /usr/bin/java java $JAVA_HOME/bin/java 1
        sudo update-alternatives --set java $JAVA_HOME/bin/java
        java -version
    
    - name: Build jar
      run: |
        mvn clean package
        
    - name: CHeck directory
      run: |
        cd targets/
        pwd
    
    - name: Copy jar to VM
      run: |
        scp -i ${{secrets.PEM_KEY}} /target/springboot-blog-webapp-0.0.1-SNAPSHOT.jar ec2-user@52.86.63.120:~/
      
  deliverToS3:
    runs-on: ubuntu-latest
    needs: [buildJar]
    
    steps:
    - name: Print message
      run: echo "This job is for copy jar to aws s3"
      
  updateApp:
    runs-on: ubuntu-latest
    needs: [deliverToS3]
    
    steps:
    - name: Print message
      run: echo "This job is for rebuild docker container"
