name: AutomationForBlogApp
env:
  APP_NAME: "blogapp"
  DEPLOY_PACKAGE_NAME: "jar-app-ver${{github.sha}}" 

on:
  push:
    branches:
      - main
      
jobs:
  buildJar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print message
      run: echo "This job is for build jar"
    
    - name: Git clone
      uses: actions/checkout@v1
    
    - name: List files
      run: ls -la
      
    - name: Check java
      run: java -version
      
  deliverToS3:
    runs-on: ubuntu-latest
    needs: [buildJar]
    
    steps:
    - name: Print message
      run: echo "This job is for copy jar to aws s3"
      
  updateApp:
    runs-on: ubuntu-latest
    needs: [deliverToS3]
    
    steps:
    - name: Print message
      run: echo "This job is for rebuild docker container"
