name: AutomationForBlogApp
env:
  APP_NAME: "blogapp"
  DEPLOY_PACKAGE_NAME: "jar-app-ver${{github.sha}}"
  AWS_REGION_NAME: "us-east-1"
  ACCOUNT_ID: "736639143360"

on:
  push:
    branches:
      - main
      
jobs:
  buildJar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print message
      run: echo "This job is for build jar"
    
    - name: Git clone
      uses: actions/checkout@v2
    
    - name: Configure AWS credential
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}} 
        aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
        aws-region: ${{env.AWS_REGION_NAME}}
    
    - name: List files
      run: ls -la
      
  deliverToS3:
    runs-on: ubuntu-latest
    needs: [buildJar]
    
    steps:
    - name: Print message
      run: echo "This job is for copy jar to aws s3"
      
  updateApp:
    runs-on: ubuntu-latest
    needs: [deliverToS3]
    
    steps:
    - name: Print message
      run: echo "This job is for rebuild docker container"
